import type {
  AdminCareerRole,
  AdminRoadmap,
  AdminTemplate,
} from "@/types/admin";

export const defaultTemplates: AdminTemplate[] = [
  {
    id: "classic",
    name: "Classic",
    description: "Traditional single-column layout with clean structure.",
    status: "active",
  },
  {
    id: "modern",
    name: "Modern",
    description: "Two-column visual layout with strong sidebar style.",
    status: "active",
  },
  {
    id: "minimal",
    name: "Minimal",
    description: "Elegant whitespace-focused resume design.",
    status: "active",
  },
  {
    id: "professional",
    name: "Professional",
    description: "Structured business-style resume with clear sections.",
    status: "active",
  },
];

export const defaultCareerRoles: AdminCareerRole[] = [
  {
    id: "full-stack-developer",
    title: "Full-Stack Developer",
    description: "Builds both client and server sides of web applications.",
    keywords: [
      "React",
      "Node.js",
      "TypeScript",
      "REST API",
      "SQL",
      "MongoDB",
      "Git",
      "CI/CD",
      "Agile",
    ],
    requiredSkills: [
      { name: "JavaScript", level: "advanced" },
      { name: "React", level: "advanced" },
      { name: "Node.js", level: "intermediate" },
      { name: "SQL", level: "intermediate" },
      { name: "Git", level: "intermediate" },
      { name: "TypeScript", level: "intermediate" },
      { name: "REST APIs", level: "intermediate" },
      { name: "Docker", level: "beginner" },
    ],
  },
  {
    id: "data-analyst",
    title: "Data Analyst",
    description: "Analyzes data to drive business insights and decision-making.",
    keywords: [
      "Python",
      "SQL",
      "Excel",
      "Tableau",
      "Power BI",
      "Statistics",
      "Data Cleaning",
      "Visualization",
    ],
    requiredSkills: [
      { name: "Python", level: "advanced" },
      { name: "SQL", level: "advanced" },
      { name: "Excel", level: "advanced" },
      { name: "Tableau", level: "intermediate" },
      { name: "Statistics", level: "intermediate" },
      { name: "Power BI", level: "beginner" },
    ],
  },
  {
    id: "ui-ux-designer",
    title: "UI/UX Designer",
    description: "Designs user interfaces and experiences for digital products.",
    keywords: [
      "Figma",
      "Wireframes",
      "Prototyping",
      "User Research",
      "Design Systems",
      "Typography",
      "Accessibility",
      "Case Study",
    ],
    requiredSkills: [
      { name: "Figma", level: "advanced" },
      { name: "User Research", level: "intermediate" },
      { name: "Prototyping", level: "intermediate" },
      { name: "HTML/CSS", level: "intermediate" },
      { name: "Design Systems", level: "intermediate" },
      { name: "Accessibility", level: "beginner" },
    ],
  },
  {
    id: "devops-engineer",
    title: "DevOps Engineer",
    description: "Automates deployments and manages infrastructure systems.",
    keywords: [
      "Linux",
      "Docker",
      "Kubernetes",
      "AWS",
      "CI/CD",
      "Shell Scripting",
      "Monitoring",
      "Terraform",
    ],
    requiredSkills: [
      { name: "Linux", level: "advanced" },
      { name: "Git", level: "intermediate" },
      { name: "Docker", level: "intermediate" },
      { name: "CI/CD", level: "intermediate" },
      { name: "AWS", level: "beginner" },
      { name: "Shell Scripting", level: "intermediate" },
    ],
  },
  {
    id: "mobile-app-developer",
    title: "Mobile App Developer",
    description: "Builds mobile applications for Android and iOS platforms.",
    keywords: [
      "Flutter",
      "React Native",
      "Firebase",
      "API Integration",
      "Mobile UI",
      "Android",
      "iOS",
      "State Management",
    ],
    requiredSkills: [
      { name: "Flutter", level: "intermediate" },
      { name: "React Native", level: "intermediate" },
      { name: "Firebase", level: "beginner" },
      { name: "API Integration", level: "intermediate" },
      { name: "Mobile UI", level: "intermediate" },
    ],
  },
];

export const defaultRoadmaps: AdminRoadmap[] = [
  {
    id: "roadmap-full-stack-developer",
    careerRoleId: "full-stack-developer",
    careerRoleName: "Full-Stack Developer",
    steps: [
      {
        id: "fs-1",
        title: "Master HTML, CSS & JavaScript",
        description: "Build a strong frontend foundation.",
        type: "Skill",
      },
      {
        id: "fs-2",
        title: "Learn React & Component Architecture",
        description: "Create reusable UI components and manage state.",
        type: "Skill",
      },
      {
        id: "fs-3",
        title: "Build a Portfolio Website",
        description: "Showcase your skills and projects online.",
        type: "Project",
      },
      {
        id: "fs-4",
        title: "Learn Node.js & Express",
        description: "Build backend APIs and server logic.",
        type: "Skill",
      },
      {
        id: "fs-5",
        title: "Database Fundamentals (SQL + NoSQL)",
        description: "Work with relational and document databases.",
        type: "Skill",
      },
      {
        id: "fs-6",
        title: "TypeScript Certification",
        description: "Validate your understanding of typed JavaScript.",
        type: "Certification",
      },
      {
        id: "fs-7",
        title: "Build a Full-Stack CRUD App",
        description: "Create a complete application with frontend and backend.",
        type: "Project",
      },
      {
        id: "fs-8",
        title: "Learn Docker & CI/CD Basics",
        description: "Understand containerization and deployment automation.",
        type: "Skill",
      },
      {
        id: "fs-9",
        title: "AWS Cloud Practitioner",
        description: "Learn cloud basics for deployment and hosting.",
        type: "Certification",
      },
      {
        id: "fs-10",
        title: "Software Engineering Internship",
        description: "Gain hands-on industry experience.",
        type: "Internship",
      },
    ],
  },
  {
    id: "roadmap-data-analyst",
    careerRoleId: "data-analyst",
    careerRoleName: "Data Analyst",
    steps: [
      {
        id: "da-1",
        title: "Learn Python for Data Analysis",
        description: "Master pandas, numpy, and matplotlib.",
        type: "Skill",
      },
      {
        id: "da-2",
        title: "SQL Mastery",
        description: "Learn joins, aggregations, filters, and advanced SQL.",
        type: "Skill",
      },
      {
        id: "da-3",
        title: "Statistics & Probability",
        description: "Understand analytical reasoning and data interpretation.",
        type: "Skill",
      },
      {
        id: "da-4",
        title: "Build a Data Dashboard Project",
        description: "Create a dashboard using Tableau or Power BI.",
        type: "Project",
      },
      {
        id: "da-5",
        title: "Google Data Analytics Certificate",
        description: "Complete a recognized analytics certification.",
        type: "Certification",
      },
      {
        id: "da-6",
        title: "Data Analysis Internship",
        description: "Apply analytical skills in real business scenarios.",
        type: "Internship",
      },
    ],
  },
  {
    id: "roadmap-ui-ux-designer",
    careerRoleId: "ui-ux-designer",
    careerRoleName: "UI/UX Designer",
    steps: [
      {
        id: "ux-1",
        title: "Learn Figma Fundamentals",
        description: "Design interfaces and prototype flows.",
        type: "Skill",
      },
      {
        id: "ux-2",
        title: "User Research Basics",
        description: "Understand users through research methods.",
        type: "Skill",
      },
      {
        id: "ux-3",
        title: "Build Wireframes & Prototypes",
        description: "Practice low and high fidelity prototyping.",
        type: "Project",
      },
      {
        id: "ux-4",
        title: "Design Systems Fundamentals",
        description: "Create scalable and consistent design systems.",
        type: "Skill",
      },
      {
        id: "ux-5",
        title: "Create UX Case Study Portfolio",
        description: "Document your problem-solving and design process.",
        type: "Project",
      },
      {
        id: "ux-6",
        title: "UI/UX Internship",
        description: "Gain product design experience in a real team.",
        type: "Internship",
      },
    ],
  },
];