export const targetRoles = [
  "No target role",
  "Full-Stack Developer",
  "Data Analyst",
  "UI/UX Designer",
  "DevOps Engineer",
  "Mobile App Developer",
];

export const roleKeywords: Record<string, string[]> = {
  "Full-Stack Developer": [
    "react",
    "next.js",
    "javascript",
    "typescript",
    "node.js",
    "express",
    "sql",
    "mongodb",
    "api",
    "git",
  ],
  "Data Analyst": [
    "python",
    "sql",
    "excel",
    "tableau",
    "power bi",
    "statistics",
    "pandas",
    "numpy",
    "dashboard",
    "analytics",
  ],
  "UI/UX Designer": [
    "figma",
    "wireframes",
    "prototyping",
    "user research",
    "design systems",
    "typography",
    "accessibility",
    "ux",
    "ui",
    "case study",
  ],
  "DevOps Engineer": [
    "linux",
    "git",
    "docker",
    "ci/cd",
    "aws",
    "azure",
    "jenkins",
    "kubernetes",
    "shell",
    "deployment",
  ],
  "Mobile App Developer": [
    "flutter",
    "react native",
    "android",
    "ios",
    "firebase",
    "api integration",
    "mobile ui",
    "dart",
    "swift",
    "kotlin",
  ],
};